.gitignore
Cargo.toml
src/lib.rs

(technically works on stable, for crates that want that, though it
actually relies on jemalloc, so it's not really stable)

A compiling copy of the Servo HeapSizeOf trait

---

Cargo.toml
src/lib.rs

Needed for `rust-selectors`, which needs to be able to use the hasher feature.

Add the unstable feature to the Cargo.toml.

---

Cargo.toml

We should probably upload the plugin there, too. [That is blocking implementations.](https://github.com/servo/string-cache/pull/105)

Increment the version, to update on Crates.

---

src/lib.rs

Hyper uses it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/15)

Add support for `Cow`.

---

Cargo.toml
src/lib.rs

Needed for servo/rust-url#135.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/16)

Add Ipv4Addr and Ipv6Addr for use in rust-url

---

Cargo.toml

Somehow crates.io already has a 0.1.2, probably was published without a merge
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/17)

Bump crates, again

---

src/lib.rs

Forgot the size of the T field itself in the list nodes.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/25)

Fix the implementation of HeapSizeOf for LinkedList

---

Cargo.toml
src/lib.rs

These fixes are in support of servo/servo#9593
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/40)

Windows support

---

Cargo.toml
src/lib.rs

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/42)

impl HeapSizeOf for VeqDeque

---

.travis.yml
Cargo.toml
build.rs
src/lib.rs

Fixes #43, fixes #44.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/46)

Fix linking on Rust versions that unprefix jemalloc

---

Cargo.toml
appveyor.yml
src/lib.rs
tests/tests.rs

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/45)

Use AppVeyor

---

src/lib.rs

At the moment we implement `HeapSizeOf` for pairs, but not for any larger tuples. This PR implements `HeapSizeOf` for tuples up to length 5.

Added impl HeapSizeOf for tuples of length up to 5.

---

src/lib.rs

Currently, in the heap size computation for HashMap, the bucket size is computed as the sum of the sizes of the key and the value. However, the buckets also contain a `usize` hash code:
https://github.com/rust-lang/rust/blob/b33386061135c3916516942de2a8ee1783e9e33a/src/libstd/collections/hash/table.rs#L89
If I understand correctly, this should be added too to the bucket size?

Count the hash code in every bucket of Hash{Map,Table}.

---

derive/lib.rs
derive/test.rs

Removes the now unneccessary feature attributes to be able to compile the crate with the current beta release.

Make it compile with the current beta release branch

---

src/lib.rs

I'm assuming this was accidentally public on Windows?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/76)

Make heap_size_of_impl consistently private

---

src/lib.rs

These return 0 since we don't know if the pointer is valid or not. This
is a bit dubious, but is designed to support cases like LinkedHashMap
where you have some data structure like a HashMap used with raw pointers
in its type parameters. We want to be able to rely on the standard
HeapSizeOf implementation for HashMap, and then do the extra bookkeeping
of managing the space consumed by the raw pointers ourselves.
I'm not sure if this is the "right" approach or not, but it seems slightly preferable to the alternative of manually copying the HashMap size estimate into LinkedHashMap and trying to keep it in sync with this crate's.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsiz …

Implement HeapSizeOf for raw pointers

---

Cargo.toml
tests/tests.rs

Fix #74
Distributions packages can use `cargo test --features flexible-tests`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/79)

Add opt in for weaker tests, for non-jemalloc allocators.

---

Cargo.toml
src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/81)

Accommodate change of empty vector representation in nightly libstd.

---

Cargo.toml

rust-url would like to depend on a relicensed version of heapsize. (https://github.com/servo/rust-url/issues/317).
The re-licensing has already happened, but a version bump (at least minor version) and re-publishing on crates.io is required for that.
This PR simply bumps the version to `0.4.1`. Once this get's published to crates.io, other crates can depend on heapsize with MIT/apache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/85)

Bump version to 0.4.1 to reflect re-licensing.

---

src/lib.rs

Ability to build heapsize for iOS platform have been added in this PR.
For building could be used:
cargo build --target aarch64-apple-ios
r? @larsbergstrom , could you, please, make code review and accept changes?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/88)

Add iOS support

---

.travis.yml

If there is no reason to keep backwards compatibility with `rust 1.8.0`, let's bump *.travis.yml* to `rust 1.9.0`.
Hopefully it will help with travis build issue described in https://github.com/travis-ci/travis-ci/issues/9128
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/95)

Bump rust version used by travis to 1.11
