.gitignore, .travis.yml, Cargo.toml, plugin/Cargo.toml, plugin/src/heap_size.rs, plugin/src/lib.rs
=> Add the compiler plugin

src/lib.rs
=> Add `PhantomData`.

plugin/src/heap_size.rs
=> Upgrade to rustc 1.4.0-nightly (f3f23bf9c 2015-08-30)

Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/19)
=> Update to libc 0.2.

plugin/Cargo.toml, plugin/src/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/20)
=> Update to Rust nightly.

plugin/src/heap_size.rs, plugin/src/lib.rs
Merge it when you think it's appropriate.
Reference:
https://github.com/rust-lang/rust/commit/9410bfa0cd68947a1f4b21c3b624855cf5732a7a
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/21)
=> Fix for latest nightly

Cargo.toml, src/lib.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/22)
=> Implement HeapSizeOf for PhantomData<T> without bounds on T

src/lib.rs
We just count 2 additional pointers per item in the list.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/24)
=> Remove the LinkedList hack

src/lib.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/26)
=> Support BTreeMap

src/lib.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/27)
=> Change the bound for HashMap to use BuildHasher

src/lib.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/29)
=> Support char

Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/30)
=> Bump to 0.2.2

Cargo.toml, src/lib.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/32)
=> Support Atomic types

src/lib.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/33)
=> Implement HeapSizeOf for () and Result<T, E>

Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/34)
=> Bump to 0.2.4

Cargo.toml, src/lib.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/35)
=> Implement HeapSizeOf for &'static str

.travis.yml, Cargo.toml, plugin/Cargo.toml, plugin/tests/tests.rs, src/lib.rs, tests/tests.rs
See individual commit messages.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/36)
=> unsafe, no libc, tests, generalize

plugin/src/heap_size.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/39)
=> Upgrade to rustc 1.8.0-nightly (4b2c7030f 2016-02-12)

.travis.yml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/47)
=> Test OS X on Travis

Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/48)
=> Bump to 0.3.3

plugin/Cargo.toml, plugin/src/heap_size.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/51)
=> Upgrade to rustc 1.8.0-nightly (0ef8d4260 2016-02-24)

src/lib.rs, tests/tests.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/52)
=> Implement HeapSizeOf for boxed slices

Cargo.toml, build.rs
Hopefully fixes https://github.com/servo/heapsize/pull/44#issuecomment-187935883.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/49)
=> Fix build script when the rustc commit date is unknown.

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/53)
=> Add a basic README with link to API docs.

src/lib.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/50)
=> HeapSizeOf for HashSet

.gitignore, .travis.yml, derive/Cargo.toml, derive/lib.rs
=> Add a heapsize_derive crate based on Macros 1.1

derive/Cargo.toml, derive/lib.rs
Hopefully will fix some "unused attributes" warnings.
=> derive: removed ignore_heap_size_of attributes

Cargo.toml
r? @nox
cc @sfackler
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/78)
=> Bump to 0.3.9

Cargo.toml, LICENSE-APACHE, LICENSE-MIT, README.md, derive/Cargo.toml, derive/lib.rs, src/lib.rs, tests/tests.rs
Read https://github.com/servo/heapsize/issues/31 for the comprehensive sign-off from all contributors.
Closes #31
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/83)
=> Relicense to MIT/Apache2

tests/tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/90)
=> Upgrade to rustc 1.22.0-nightly (7778906be 2017-10-14)

Cargo.toml, src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/89)
=> Support Range<T>, RangeFrom<T>, RangeTo<T> and RangeFull

README.md
Fixes #92.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/94)
=> Update API docs link.

Cargo.toml, src/lib.rs
reopened #91
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/heapsize/93)
=> Update winapi to 0.3.4
